# This is the jni directory.
LOCAL_PATH := $(call my-dir)

# This file is to be generated by CMake.  We reference files within this
# Allegro source tree and not installed into the toolchain directory,
# which complicates things slightly.
include $(LOCAL_PATH)/localgen.mk

# Declare Allegro libraries, which are NOT built with ndk-build.
include $(CLEAR_VARS)
LOCAL_MODULE := allegro
LOCAL_SRC_FILES := $(RELATIVE_LIB_DIR)/lib$(LOCAL_MODULE)$(LIB_TYPE_SUFFIX).so
LOCAL_EXPORT_C_INCLUDES := $(CMAKE_SOURCE_DIR)/include
LOCAL_EXPORT_C_INCLUDES += $(CMAKE_BINARY_DIR)/include
LOCAL_EXPORT_C_LDLIBS := -llog
LOCAL_EXPORT_CFLAGS := -DDEBUGMODE
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := allegro_image
LOCAL_SRC_FILES := $(RELATIVE_LIB_DIR)/lib$(LOCAL_MODULE)$(LIB_TYPE_SUFFIX).so
LOCAL_EXPORT_C_INCLUDES += $(CMAKE_SOURCE_DIR)/addons/image
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := allegro_primitives
LOCAL_SRC_FILES := $(RELATIVE_LIB_DIR)/lib$(LOCAL_MODULE)$(LIB_TYPE_SUFFIX).so
LOCAL_EXPORT_C_INCLUDES := $(CMAKE_SOURCE_DIR)/addons/primitives
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := allegro_font
LOCAL_SRC_FILES := $(RELATIVE_LIB_DIR)/lib$(LOCAL_MODULE)$(LIB_TYPE_SUFFIX).so
LOCAL_EXPORT_C_INCLUDES := $(CMAKE_SOURCE_DIR)/addons/font
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := allegro_ttf
LOCAL_SRC_FILES := $(RELATIVE_LIB_DIR)/lib$(LOCAL_MODULE)$(LIB_TYPE_SUFFIX).so
LOCAL_EXPORT_C_INCLUDES := $(CMAKE_SOURCE_DIR)/addons/ttf
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
#LOCAL_MODULE := nano-X
LOCAL_MODULE := PX11
LOCAL_SRC_FILES := $(RELATIVE_LIB_DIR)/lib$(LOCAL_MODULE).a
LOCAL_EXPORT_C_INCLUDES := $(CMAKE_SOURCE_DIR)/include
LOCAL_EXPORT_C_INCLUDES += $(CMAKE_BINARY_DIR)/include
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := fltk
LOCAL_SRC_FILES := $(RELATIVE_LIB_DIR)/lib$(LOCAL_MODULE).a
LOCAL_EXPORT_C_INCLUDES := $(CMAKE_SOURCE_DIR)/include
LOCAL_EXPORT_C_INCLUDES += $(CMAKE_BINARY_DIR)/include
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := freetype-android
LOCAL_SRC_FILES := $(RELATIVE_LIB_DIR)/lib$(LOCAL_MODULE).a
LOCAL_EXPORT_C_INCLUDES := $(CMAKE_SOURCE_DIR)/include
LOCAL_EXPORT_C_INCLUDES += $(CMAKE_BINARY_DIR)/include
include $(PREBUILT_STATIC_LIBRARY)


# Declare our application.
# Source files are relative to $(LOCAL_PATH).
include $(CLEAR_VARS)
LOCAL_MODULE    := exnanox
#LOCAL_SRC_FILES := ../csrc/ex_ttf.cpp
LOCAL_SRC_FILES := ../csrc/ex_nanox.c
LOCAL_CFLAGS    += -W -Wall -g 
#LOCAL_CFLAGS    += -frtti
LOCAL_LDFLAGS += -L/home/georg/android-toolchain/sysroot/usr/lib -llog -lz
LOCAL_SHARED_LIBRARIES := allegro
LOCAL_SHARED_LIBRARIES += allegro_image
LOCAL_SHARED_LIBRARIES += allegro_primitives
LOCAL_SHARED_LIBRARIES += allegro_font
LOCAL_SHARED_LIBRARIES += allegro_ttf
#LOCAL_STATIC_LIBRARIES += fltk
LOCAL_STATIC_LIBRARIES += PX11
#LOCAL_STATIC_LIBRARIES += nano-X
LOCAL_STATIC_LIBRARIES += freetype-android
include $(BUILD_SHARED_LIBRARY)
